// Generated by uniffi-bindgen-react-native
#include "react-native-harrys-password-manager-core.h"
#include "generated/harrys_password_manager_core.hpp"

namespace harryspasswordmanagercore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeHarrysPasswordManagerCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}