// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-harrys-password-manager-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "HarrysPasswordManagerCoreSpec.h"

@interface HarrysPasswordManagerCore : NSObject <NativeHarrysPasswordManagerCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface HarrysPasswordManagerCore : NSObject <RCTBridgeModule>
#endif

@end